:building_construction: comment model
SELab-2/Dr-Trottoir-2 pull request #252
Opened 2023-04-19 14:39 UTC by wwelvaer

See issues #237, #260, #280
Also fixed an issue where the automatically filled out created_at field in photos was not saved properly.

2023-05-02 18:21 UTC, BrentBlanckaert requested changes
Looks really good, but could you maybe try to add the new models to the [django administration](http://localhost:8000/admin/)

2023-05-04 12:05 UTC, BrentBlanckaert requested changes
It's added but isn't there also a comment object because that isn't present.

2023-05-05 18:47 UTC, wwelvaer commented
> It's added but isn't there also a comment object because that isn't present.

No, the Comment Model is an abstract model and cannot be used separately

2023-05-05 18:48 UTC, BrentBlanckaert approved these changes

2023-05-05 18:48 UTC, merged