:sparkles: 229 planning student
SELab-2/Dr-Trottoir-2 pull request #269
Opened 2023-04-20 17:03 UTC by BrentBlanckaert

planning page for student. Will show all tour that are assigned to the current user in this week.
![image](https://user-images.githubusercontent.com/125136419/235468821-14aeb677-063a-4800-aff2-8d8c88bbf998.png)

Closes #229

2023-05-05 13:46 UTC, eliasnijs requested changes
**Functionality:**
- Does not work as student.

**Styling:**
- Titles are redundant and should be removed.
- Dropdown should be full width.
- Checkboxes are to large.

**Other:**
- It would be nice if you could put some data in the fixtures for this page.

2023-05-05 18:44 UTC, BrentBlanckaert commented
> **Functionality:**
> 
> * Does not work as student.
> 
This works just fine for me

> **Other:**
> 
> * It would be nice if you could put some data in the fixtures for this page.

It would be very hard to add fixtures for this since this would change every week.

2023-05-06 18:42 UTC, BrentBlanckaert commented
the new look of the planning page after a few style changes
![image](https://user-images.githubusercontent.com/125136419/236641403-a556f99e-1ff6-4929-927b-e6e1a08d063e.png)

2023-05-17 09:26 UTC, eliasnijs approved these changes

2023-05-17 09:26 UTC, merged