:sparkles: fixed comments in /admin/planningen #299
SELab-2/Dr-Trottoir-2 pull request #306
Opened 2023-05-07 19:18 UTC by BrentBlanckaert

Closes #299

2023-05-10 23:00 UTC, milachae requested changes
Looks good, remove the console.logs

2023-05-10 23:00 UTC, milachae commented on frontend/src/pages/admin/planningen/[pid].jsx
> +        console.log(user);
remove this.

2023-05-10 23:00 UTC, milachae commented on frontend/src/pages/admin/planningen/[pid].jsx
> +      console.log(comments);
remove this

2023-05-14 21:56 UTC, milachae approved these changes

2023-05-14 22:01 UTC, milachae commented
@BrentBlanckaert 
The button on the planning page forwards you to /planning/<id> and not /planningen/<id>, 2 options here:
* change the detailed page to planning
* change the main page to planningen and change the title in the navbar to planningen

2023-05-15 09:22 UTC, BrentBlanckaert commented
> @BrentBlanckaert The button on the planning page forwards you to /planning/ and not /planningen/, 2 options here:
> 
> * change the detailed page to planning
> * change the main page to planningen and change the title in the navbar to planningen

This should be fixed in the PR #307

2023-05-15 09:23 UTC, merged