:sparkles: page user add
SELab-2/Dr-Trottoir-2 pull request #334
Opened 2023-05-18 18:02 UTC by milachae

Closes #333, Closes #319

2023-05-19 15:14 UTC, bertcappelle commented on frontend/src/components/LayoutDataToevoegen.jsx
> +                {data.active ? "Active" : "Inactive"}
Translate to Dutch

2023-05-19 16:32 UTC, renevds requested changes
Can you make the text of disabled fields (like name and stuff) a lighter colour.

2023-05-19 17:05 UTC, milachae commented on frontend/src/components/LayoutDataToevoegen.jsx
> +                {data.active ? "Active" : "Inactive"}
This is fixed now!

2023-05-19 17:07 UTC, milachae commented
@renevds 
> Can you make the text of disabled fields (like name and stuff) a lighter colour.

I already tried to make it a lighter colour, but the other possible options was to light.
![image](https://github.com/SELab-2/Dr-Trottoir-2/assets/95340152/763832d8-db46-4577-9989-6301f8c0b302)

I can add a new colour to fix this?

2023-05-19 17:09 UTC, renevds commented
A new colour sounds good to me!

2023-05-19 17:13 UTC, bertcappelle approved these changes

2023-05-19 17:19 UTC, milachae commented
@renevds 

I tried adding a new colour:
![image](https://github.com/SELab-2/Dr-Trottoir-2/assets/95340152/08f912e7-0b54-4bce-bdc6-a4f309dc0925)

2023-05-20 14:41 UTC, renevds approved these changes
GJ

2023-05-20 14:41 UTC, merged