Refactor front
SELab-2/Dr-Trottoir-2 pull request #347
Opened 2023-05-20 14:54 UTC by renevds

2023-05-20 22:48 UTC, JasperJanin submitted a review, later dismissed

2023-05-20 22:49 UTC, JasperJanin commented
@renevds Maybe change the switch button on student view to "naar beheer"
![image](https://github.com/SELab-2/Dr-Trottoir-2/assets/55832482/a75ee182-319d-4250-a2eb-564fed9d444f)

Still approved because original had this as well

2023-05-21 08:42 UTC, milachae requested changes
remove the console.logs

2023-05-21 08:55 UTC, milachae requested changes
Most of the things are working!
- The navbar features seems to work fine.
- The sorting is also working
- I was not able to test the mapview, because I have no up to date API key

How does the mapview behave when no buildings are present? I was not able to test this.

Remove some console.log()

2023-05-21 08:55 UTC, milachae commented on frontend/src/components/forms/forms-components/TourBuildingAdd.jsx
> +
Remove the console.log()

2023-05-21 10:25 UTC, renevds commented
With no buildings, it just shows an empty map.

2023-05-21 10:27 UTC, milachae approved these changes

2023-05-21 10:30 UTC, merged